### ISSUE TITLE
Logger instrumentation files should be prefixed

### ISSUE THREAD

**Issue by nicokant** [NINAnor/seabird-gps-database#10]
Logger instrumentation table describe a single file, but doesn't use a constraint on `filename` column, so inside the table can exist multiple files with the same name https://github.com/NINAnor/seabird-gps-database/blob/a2aa1e8e3f53c96e87dac93f8458817b7e7a88ff/db/migrations/20231011112823_logger.sql#L21
In the file system instead, inside a directory only a file can exist with a given name, so uploading multiple files with the same name can have a misleading behavior.

The upload process should:
- use a prefix for the filename or a put the file in a directory (in both cases the prefix should be the PK of the row)
- wait for the database INSERT transaction to finish

https://github.com/NINAnor/seabird-gps-database/blob/a2aa1e8e3f53c96e87dac93f8458817b7e7a88ff/wizard/wizard.py#L72

**Comment by frafra** [comment]
We should also take care of the migration of the deployed system, by writing a script to move the files.
