### ISSUE TITLE
Column name inconsistencies

### ISSUE THREAD

**Issue by nicokant** [NINAnor/seabird-gps-database#14]
the `_logger_mass_g` field has different names for each sensor:
- `mass_gps_logger_g` for gps
- `gls_logger_mass_g` for gls
- `tdr_mass_g` for tdr
- `other_sensor_logger_mass_g` for other_sensor

We should have a shared suffix and way of naming fields

**Comment by frafra** [comment]
I also found some other differences/inconsistencies:
- gps and gls use `deployment_retrieval_time_zone`, tdr and other_sensor use `startup_deployment_retrieval_time_zone`
- gps has `logger_comment`, gls has `comments`, tdr and other_sensor use `comment`

To be aware:
- gls use `_gmt` as prefix for `startup_date` and `startup_time`
- `record_frequency` is in seconds for gps and tdr, gls uses minutes, and other_sensor uses milliseconds
- the order of the columns is different

**Comment by ninadehnhard** [comment]
oh, these are very good points. We should indeed fix these in the metadatasheet (and the database). So we'd have to change the column-names in the metada-files. That would be a job for Vilde to do. 

I tend to say that we should use seconds throughout as record_frequency

**Comment by vilde-oddvik** [comment]
I am on it! I will send you the updated metadata v6 when it is done.

**Comment by nicokant** [comment]
Implemented in 18146e0a7fa193947b957b98cf63d97dbcdece54

Here is the updated metadata structure in XLSX: [GPS_database_Metadatafile_v6.xlsx](https://github.com/NINAnor/seabird-gps-database/files/14613112/GPS_database_Metadatafile_v6.xlsx)
