### ISSUE TITLE
Is total_logger_mass_all_loggers_g redundant?

### ISSUE THREAD

**Issue by frafra** [NINAnor/seabird-gps-database#15]
We have four types of loggers (gps/gls/tdr + generic), and each one of them have a mass specified. We also have `total_logger_mass_all_loggers_g` as column.

@ninadehnhard Should we compute the sum of the logger mass when this column is empty? Should we check for consistency when this column contains data?

**Comment by ninadehnhard** [comment]
oh, that's a tricky one. I am afraid that quite often the individual logger masses are not specified, but the total_logger_mass_all_loggers_g might be specified. Or there are individual logger masses, but not all of them are specified. In principle it would be great to have a consistency/plausibility check for this, but in practice, I think it will give us a lot of problems, so I tend so say: don't do it

**Comment by frafra** [comment]
Thank you Nina :)
