### ISSUE TITLE
gls_data_collected "unknown"

### ISSUE THREAD

**Issue by nicokant** [NINAnor/seabird-gps-database#16]
@ninadehnhard in the file `Black_Guillemots_Muddvær+Sklinna_2018-2021_v5` the column `gls_data_collected` allows as value `unknown`, how should it be treated?

**Comment by ninadehnhard** [comment]
@nicokant good catch! If gls_data_collected = "unknown" treat it the same as gls_data_collected = no. 
So, only if gls_data_collected = "yes" and it is not for SEATRACK, then you should expect a data-file-name
I hope this makes sense?

**Comment by nicokant** [comment]
Totally, thank you!
