### ISSUE TITLE
GPS and Accelerometer in one big file

### ISSUE THREAD

**Issue by vilde-oddvik** [NINAnor/seabird-gps-database#20]
We have 8 huge csv files (>500MB) where the GPS data is in the same file as accelerometer data (other sensor). Is there any way we can get both of these data into the database? The upload size limit is also an issue here.

You can find the files in: P:\12690082_seapop_predikerte_funksjonsomrader_i_hekketiden\Workfolder_for_database\original_files\Brünnich's Guillemots_Svalbard_fromSeb\csv-kml files-all years and colonies\csv files of axytrek loggers

**Comment by nicokant** [comment]
I see two different problems here:
1. Uploading big files/lots of files
2. Accelerometer and GPS data in the same file

I'm going to open a new issue about the upload size, as it will require some discussion.

About the accelerometer and GPS data, there is no problem, we are not going to import them inside the database, but we are going to produce a "standalone database" for each file in a format called `parquet`. I have to write some code to handle this new format.

**Comment by nicokant** [comment]
implemented in ce619d9559afecafd1c1526dcd610d1b8ffc9d2d
