### ISSUE TITLE
Spreadsheet structure does not match

### ISSUE THREAD

**Issue by vilde-oddvik** [NINAnor/seabird-gps-database#23]
I get this error when trying to upload a metadata spreadsheet v6. I assume that if I press "ignore", then the extra columns will not be included in the database, so I dont want to do that.

![Picture1](https://github.com/NINAnor/seabird-gps-database/assets/163317685/1eb97847-5914-4374-8ade-7595d9ba5414)

**Comment by nicokant** [comment]
Could you upload the file on R/Kladd?

**Comment by vilde-oddvik** [comment]
Yes, done

**Comment by nicokant** [comment]
fixed in 42bd61f81d29ddb0a9d48f685cdbec638fb958fa and deployed
