### ISSUE TITLE
Error: Old ring number specified, but not present in the database

### ISSUE THREAD

**Issue by vilde-oddvik** [NINAnor/seabird-gps-database#24]
I seem to be getting this error when the spreadsheets has ring numbers with letters in, in the "old_ring_number" column. 

![image](https://github.com/NINAnor/seabird-gps-database/assets/163317685/2b4b2e2a-9cb4-4afe-8f92-3a7ad75e357a)

Same error in both these files:
[LBBG_Karmøy_2023_v6.xlsx](https://github.com/NINAnor/seabird-gps-database/files/14903135/LBBG_Karmoy_2023_v6.xlsx)
[Puffin_Runde_2020-2023_v6.xlsx](https://github.com/NINAnor/seabird-gps-database/files/14903136/Puffin_Runde_2020-2023_v6.xlsx)

**Comment by nicokant** [comment]
When using `old_ring_number` the database expects that there is already a ring in the database with that name, in this case it means that you should upload first the metadata file containing that ring_number, otherwise it's not possible to reference it

**Comment by vilde-oddvik** [comment]
Okay, I see!
