### ISSUE TITLE
New error when uploading metadata

### ISSUE THREAD

**Issue by vilde-oddvik** [NINAnor/seabird-gps-database#27]
I get the following error when trying to upload this metadata

[Kittiwake_Spitsbergen_2013-2022_v6.xlsx](https://github.com/user-attachments/files/15872011/Kittiwake_Spitsbergen_2013-2022_v6.xlsx)

![image](https://github.com/NINAnor/seabird-gps-database/assets/163317685/7571d84d-9c17-4a35-9d15-648948b89361)

**Comment by vilde-oddvik** [comment]
Is this a new thing? None of the other excel files I have uploaded have been called METADATA?

**Comment by nicokant** [comment]
Not the excel files, the sheet name, in each excel file you can have
multiple sheets, we import only the one named METADATA

**Comment by vilde-oddvik** [comment]
Ah, okay! Thanks
