### ISSUE TITLE
New GPS logger file format

### ISSUE THREAD

**Issue by vilde-oddvik** [NINAnor/seabird-gps-database#28]
We have gotten data from 5 new loggers with a new file format that needs to be allowed in the database. GPS logger type is Ecotone, here is an example file:

[10_raw_csv_format.txt](https://github.com/user-attachments/files/15885161/10_raw_csv_format.txt)

The column headers are: Device ID; Day; Month; Year; Hour; Minute; Latitude; Longitude; Parameter

(Logger type so far only used on kittiwakes, Sør-Gjæslingane, 2014)

**Comment by vilde-oddvik** [comment]
These GPS file formats are also not supported in the database:

[BK_logg161_120708.LOG](https://github.com/user-attachments/files/15886406/BK_logg161_120708.LOG)
[G199_120708.TXT](https://github.com/user-attachments/files/15886407/G199_120708.TXT)

**Comment by nicokant** [comment]
@vilde-oddvik do you know which kind of logger devices are the last 2 files?

**Comment by vilde-oddvik** [comment]
Both are gps, model Earth&Ocean mGPS-2

**Comment by nicokant** [comment]
Perfect, thank you!

These files don't have name for the columns, do you know the column names?

**Comment by vilde-oddvik** [comment]
Yes, I believe it is:

[BK_logg161_120708.LOG](https://github.com/user-attachments/files/15886406/BK_logg161_120708.LOG):
Day; Time; Latitude; Longitude; Satellite; Voltage; Speed; Altitude; Distance 

[G199_120708.TXT](https://github.com/user-attachments/files/15886407/G199_120708.TXT):
Date; Time; Latitude; Longitude; Satellite; Voltage; Speed; Altitude; Distance
