### ISSUE TITLE
Improve upload wizard

### ISSUE THREAD

**Issue by frafra** [NINAnor/seabird-gps-database#7]
The current wizard could be improved.

For example, the error message contains a JSON representation of the row which triggered the error: it would be nice to represent it as HTML table. In addition to that, users have to refresh/reload the page to upload new files.

The overall experience is not great and the wizard needs some love.

**Comment by nicokant** [comment]
To improve UX it could also be useful providing a runtime user "mapping" of the extra/missing fields
